version: '3.8'

services:
  publisher:
    image: postgres:16
    container_name: publisher
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: log_db
    ports:
      - "5436:5432"

  subscriber:
    image: postgres:16
    container_name: subscriber
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: log_db
    ports:
      - "5437:5432"
