services:
  queue_db:
    image: postgres:16
    container_name: queue_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: logist_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
